wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1679181720.615468
    t:
      1:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
max_depth:
  desc: null
  value: null
max_features:
  desc: null
  value: sqrt
max_leaf_nodes:
  desc: null
  value: null
max_samples:
  desc: null
  value: null
min_impunity_decrease:
  desc: null
  value: 0.0
min_samples_lead:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 2
min_weight_fraction_leaf:
  desc: null
  value: 0.0
n_estimators:
  desc: null
  value: 100
