wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1679185754.612191
    t:
      1:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 0.1
max_iter:
  desc: null
  value: 10000
random_state:
  desc: null
  value: 69
tol:
  desc: null
  value: 0.001
