wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1678873595.58404
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
bayesian_matrix_reg:
  desc: null
  value: []
bootstrap_type:
  desc: null
  value: []
border_count:
  desc: null
  value: []
depth:
  desc: null
  value: []
grow_policy:
  desc: null
  value: []
iterations:
  desc: null
  value: 9999
l2_leaf_reg:
  desc: null
  value: []
leaf_estimation_iterations:
  desc: null
  value: []
leaf_estimation_method:
  desc: null
  value: []
learning_rate:
  desc: null
  value: 0.15
max_leaves:
  desc: null
  value: []
min_data_in_leaf:
  desc: null
  value: []
model_size_reg:
  desc: null
  value: []
od_wait:
  desc: null
  value: []
posterior_sampling:
  desc: null
  value: []
random_seed:
  desc: null
  value: []
random_state:
  desc: null
  value: 69
random_strength:
  desc: null
  value: []
sampling_frequency:
  desc: null
  value: []
