wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: valid_0_binary_logloss
      6:
      - 3
      7:
      - 1
    python_version: 3.10.9
    start_time: 1679180863.972292
    t:
      1:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      - 25
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
    visualize:
      LGBM_Feature_Importance:
        panel_config:
          fieldSettings:
            label: label
            value: value
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Feature Importance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: LGBM_Feature_Importance_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
boosting_type:
  desc: null
  value: gbdt
colsample_bytree:
  desc: null
  value: 0.5784778854092203
early_stopping_round:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.00693702575527996
max_depth:
  desc: null
  value: 5
metric:
  desc: null
  value:
  - binary_logloss
  - logloss
min_child_samples:
  desc: null
  value: 20
min_child_weight:
  desc: null
  value: 0.001
min_split_gain:
  desc: null
  value: 0.0
n_estimators:
  desc: null
  value: 9999
n_jobs:
  desc: null
  value: -1
num_iterations:
  desc: null
  value: 9999
num_leaves:
  desc: null
  value: 31
objective:
  desc: null
  value: binary
random_state:
  desc: null
  value: 69
reg_alpha:
  desc: null
  value: 0.2622912287429849
reg_lambda:
  desc: null
  value: 2.8702494234117617e-08
subsample:
  desc: null
  value: 0.20851841295589477
subsample_for_bin:
  desc: null
  value: 200000
subsample_freq:
  desc: null
  value: 0
verbose:
  desc: null
  value: -1
