wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1678875180.089548
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 15
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
