wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1679180823.673946
    t:
      1:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
boosting_type:
  desc: null
  value: gbdt
colsample_bytree:
  desc: null
  value: 0.5784778854092203
learning_rate:
  desc: null
  value: 0.00693702575527996
max_depth:
  desc: null
  value: 5
metric:
  desc: null
  value: logloss
n_estimators:
  desc: null
  value: 9999
objective:
  desc: null
  value: binary
random_state:
  desc: null
  value: 69
reg_alpha:
  desc: null
  value: 0.2622912287429849
reg_lambda:
  desc: null
  value: 2.8702494234117617e-08
subsample:
  desc: null
  value: 0.20851841295589477
