wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    session_history: code/_session_history.ipynb
    start_time: 1678862295.285715
    t:
      1:
      - 5
      - 28
      - 53
      - 54
      - 55
      2:
      - 5
      - 6
      - 7
      - 8
      - 28
      - 53
      - 54
      - 55
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 1
      - 5
setup:
  desc: null
  value:
    CPU Jobs: -1
    Categorical imputation: mode
    Experiment Name: rm_multico-poly3-nfeatures_0.1
    Feature selection: true
    Feature selection estimator: lightgbm
    Feature selection method: classic
    Fold Generator: RepeatedStratifiedKFold
    Fold Number: 5
    Imputation type: simple
    Log Experiment: WandbLogger
    Multicollinearity threshold: 0.95
    Number of features selected: 0.1
    Numeric features: 8
    Numeric imputation: mean
    Original data shape:
    - 117564
    - 9
    Polynomial degree: 3
    Polynomial features: true
    Preprocess: true
    Remove multicollinearity: true
    Session id: 69
    Target: Class
    Target type: Binary
    Transformed data shape:
    - 117564
    - 1
    Transformed test set shape:
    - 35270
    - 1
    Transformed train set shape:
    - 82294
    - 1
    USI: 6c95
    Use GPU: false
