wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: valid_0_binary_logloss
      6:
      - 3
      7:
      - 1
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1678873916.049969
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 7
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 7
      - 15
      - 23
      - 25
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
boosting_type:
  desc: null
  value: gbdt
colsample_bytree:
  desc: null
  value: 1.0
early_stopping_round:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.00693702575527996
max_depth:
  desc: null
  value: -1
metric:
  desc: null
  value:
  - binary_logloss
  - logloss
min_child_samples:
  desc: null
  value: 20
min_child_weight:
  desc: null
  value: 0.001
min_split_gain:
  desc: null
  value: 0.0
n_jobs:
  desc: null
  value: -1
num_iterations:
  desc: null
  value: 9999
num_leaves:
  desc: null
  value: 31
objective:
  desc: null
  value: binary
random_state:
  desc: null
  value: 69
reg_alpha:
  desc: null
  value: 0.0
reg_lambda:
  desc: null
  value: 0.0
subsample:
  desc: null
  value: 1.0
subsample_for_bin:
  desc: null
  value: 200000
subsample_freq:
  desc: null
  value: 0
verbose:
  desc: null
  value: -1
