wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: validation_0-logloss
      6:
      - 3
      7:
      - 1
    python_version: 3.10.9
    session_history: code/_session_history.ipynb
    start_time: 1679178622.366455
    t:
      1:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 8
      - 35
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      - 31
      4: 3.10.9
      5: 0.14.0
      8:
      - 1
      - 5
    visualize:
      Feature Importance:
        panel_config:
          fieldSettings:
            label: Feature
            value: Importance
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Feature Importance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Feature Importance_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
colsample_bytree:
  desc: null
  value: 0.8298539920447499
gamma:
  desc: null
  value: 5.301218558776368e-08
learner:
  desc: null
  value:
    generic_param:
      fail_on_invalid_gpu_id: '0'
      gpu_id: '-1'
      n_jobs: '-1'
      nthread: '-1'
      random_state: '69'
      seed: '69'
      seed_per_iteration: '0'
      validate_parameters: '1'
    gradient_booster:
      gbtree_model_param:
        num_parallel_tree: '1'
        num_trees: '0'
        size_leaf_vector: '0'
      gbtree_train_param:
        predictor: auto
        process_type: default
        tree_method: auto
        updater: grow_colmaker,prune
        updater_seq: grow_colmaker,prune
      name: gbtree
      specified_updater: false
      updater:
        grow_colmaker:
          colmaker_train_param:
            default_direction: learn
            opt_dense_col: '1'
          train_param:
            alpha: '0.000517878099'
            cache_opt: '1'
            colsample_bylevel: '1'
            colsample_bynode: '1'
            colsample_bytree: '0.829854012'
            eta: '0.0533322208'
            gamma: '5.30121866e-08'
            grow_policy: depthwise
            interaction_constraints: ''
            lambda: '0.000301214139'
            learning_rate: '0.0533322208'
            max_bin: '256'
            max_cat_threshold: '64'
            max_cat_to_onehot: '4'
            max_delta_step: '0'
            max_depth: '4'
            max_leaves: '0'
            min_child_weight: '4'
            min_split_loss: '5.30121866e-08'
            monotone_constraints: ()
            refresh_leaf: '1'
            reg_alpha: '0.000517878099'
            reg_lambda: '0.000301214139'
            sampling_method: uniform
            sketch_ratio: '2'
            sparse_threshold: '0.20000000000000001'
            subsample: '0.410104305'
        prune:
          train_param:
            alpha: '0.000517878099'
            cache_opt: '1'
            colsample_bylevel: '1'
            colsample_bynode: '1'
            colsample_bytree: '0.829854012'
            eta: '0.0533322208'
            gamma: '5.30121866e-08'
            grow_policy: depthwise
            interaction_constraints: ''
            lambda: '0.000301214139'
            learning_rate: '0.0533322208'
            max_bin: '256'
            max_cat_threshold: '64'
            max_cat_to_onehot: '4'
            max_delta_step: '0'
            max_depth: '4'
            max_leaves: '0'
            min_child_weight: '4'
            min_split_loss: '5.30121866e-08'
            monotone_constraints: ()
            refresh_leaf: '1'
            reg_alpha: '0.000517878099'
            reg_lambda: '0.000301214139'
            sampling_method: uniform
            sketch_ratio: '2'
            sparse_threshold: '0.20000000000000001'
            subsample: '0.410104305'
    learner_model_param:
      base_score: 5E-1
      boost_from_average: '1'
      num_class: '0'
      num_feature: '3'
      num_target: '1'
    learner_train_param:
      booster: gbtree
      disable_default_eval_metric: '0'
      dsplit: auto
      objective: binary:logistic
    metrics:
    - name: logloss
    objective:
      name: binary:logistic
      reg_loss_param:
        scale_pos_weight: '1'
learning_rate:
  desc: null
  value: 0.05333221939055333
max_depth:
  desc: null
  value: 4
min_child_weight:
  desc: null
  value: 4
n_components:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 9999
reg_alpha:
  desc: null
  value: 0.000517878113716743
reg_lambda:
  desc: null
  value: 0.00030121415155097723
scaler:
  desc: null
  value: standard
subsample:
  desc: null
  value: 0.41010429946197946
version:
  desc: null
  value:
  - 1
  - 7
  - 4
