wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678736093.454757
    t:
      1:
      - 5
      - 8
      - 28
      - 53
      - 55
      2:
      - 5
      - 8
      - 28
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.9.16
      5: 0.13.11
      8:
      - 1
      - 5
setup:
  desc: null
  value:
    CPU Jobs: -1
    Categorical imputation: mode
    Experiment Name: pycaret
    Fold Generator: RepeatedStratifiedKFold
    Fold Number: 5
    Imputation type: simple
    Log Experiment: WandbLogger
    Numeric features: 8
    Numeric imputation: mean
    Original data shape:
    - 117564
    - 9
    Polynomial degree: 2
    Polynomial features: true
    Preprocess: true
    Session id: 2051
    Target: Class
    Target type: Binary
    Transformed data shape:
    - 117564
    - 45
    Transformed test set shape:
    - 35270
    - 45
    Transformed train set shape:
    - 82294
    - 45
    USI: 6e18
    Use GPU: false
